name: Publish images

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+ # include prerelease tags too

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    name: Prepare properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Prepare build parameters
        id: prep
        run: |
          hack/build/ci/prepare-build-variables.sh
      - name: Docker metadata
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4.4.0
        id: meta
        with:
          images: dynatrace/dynatrace-operator
          tags: ${{ steps.prep.outputs.docker_image_tag }}
          labels: |
            ${{ steps.prep.outputs.docker_image_labels }}
            vcs-ref=${{ github.sha }}
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      version: ${{ steps.prep.outputs.docker_image_tag }}

  build:
    name: Build images
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        platform: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Build image
        uses: ./.github/actions/build-image
        with:
          platform: ${{ matrix.platform }}
          labels: ${{ needs.prepare.outputs.labels }}
          image-tag: ${{ needs.prepare.outputs.version }}

  push:
    name: Push images
    environment: Release
    needs: [prepare, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        platform: [amd64]
        registry: [gcr, dockerhub]
        include:
        - registry: gcr
          url: gcr.io
          repository: GCR_REPOSITORY
          username: GCR_USERNAME
          password: GCR_JSON_KEY
        - registry: dockerhub
          url: quay.io
          repository: DOCKERHUB_REPOSITORY
          username: DOCKERHUB_USERNAME
          password: DOCKERHUB_PASSWORD
    steps:
      - run: echo "pushing ${{matrix.platform}} to ${{matrix.registry}}/${{matrix.repository}}"

  push-rhcc:
    name: Push amd64 image to RHCC
    if: ${{ !contains(github.ref-name, '-rc') }}
    environment: Release
    needs: [prepare, build]
    runs-on: ubuntu-latest
    env:
      SCAN_REGISTRY: "quay.io"
    steps:
      - run: echo "noo this should not happen!"
      - run: echo "${{ github.ref-name}}"
      - run: echo "${{ !contains(github.ref-name, '-rc') }}"

  manifest:
    name: Create manifest
    environment: Release
    needs: [prepare, push]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        registry: [gcr, dockerhub]
        include:
          - registry: gcr
            url: gcr.io
            repository: GCR_REPOSITORY
            username: GCR_USERNAME
            password: GCR_JSON_KEY
          - registry: dockerhub
            url: docker.io
            repository: DOCKERHUB_REPOSITORY
            username: DOCKERHUB_USERNAME
            password: DOCKERHUB_PASSWORD
    steps:
      - run: echo "this should happen again for ${{matrix.registry}}."
